"""Add avatar to users

Revision ID: 1ab58533806c
Revises: 3135f803b1ce
Create Date: 2013-02-15 07:49:08.364545

"""

# revision identifiers, used by Alembic.
revision = '1ab58533806c'
down_revision = '3135f803b1ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    ### end Alembic commands ###
