"""Add original_id to recurrences

Revision ID: 2f017f0b15b7
Revises: 4f7cbabaed5c
Create Date: 2013-02-24 22:43:13.974569

"""

# revision identifiers, used by Alembic.
revision = '2f017f0b15b7'
down_revision = '4f7cbabaed5c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurrence', sa.Column('original_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurrence', 'original_id')
    ### end Alembic commands ###
