"""add deleted column to users

Revision ID: 3135f803b1ce
Revises: 440d9bbe1d6e
Create Date: 2013-01-28 23:44:33.103419

"""

# revision identifiers, used by Alembic.
revision = '3135f803b1ce'
down_revision = '440d9bbe1d6e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user',
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deleted')
    ### end Alembic commands ###
