"""Add recurrences table

Revision ID: 4f7cbabaed5c
Revises: 1ab58533806c
Create Date: 2013-02-24 11:49:56.806576

"""

# revision identifiers, used by Alembic.
revision = '4f7cbabaed5c'
down_revision = '1ab58533806c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurrence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('yearly', sa.DateTime(), nullable=True),
    sa.Column('monthly', sa.Integer(), nullable=True),
    sa.Column('weekly', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'expense', sa.Column('recurrence_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'expense', 'recurrence_id')
    op.drop_table('recurrence')
    ### end Alembic commands ###
